services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}


  vault:
    image: hashicorp/vault:1.13.3
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.hcl
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config/vault.hcl:/vault/config/vault.hcl:ro
      - ./data:/vault/data

  config-server:
    image: max2ba/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - rabbitmq
      - vault
    environment:
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      VAULT_TOKEN: ${VAULT_TOKEN}

  service-discovery:
    image: max2ba/service-discovery:latest
    container_name: service-discovery
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - config-server
    environment:
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      CONFIG-TOKEN: ${CONFIG-TOKEN}

  gateway-service:
    image: max2ba/gateway-service
    container_name: gateway-service
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - config-server
    environment:
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      CONFIG-TOKEN: ${CONFIG-TOKEN}


  postgres-notification-service:
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_DB: ${NOTIFICATION_DB_NAME}
      POSTGRES_USER: ${NOTIFICATION_DB_USERNAME}
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
    ports:
      - "${NOTIFICATION_DB_PORT}:5432"

  notification-service:
    image: max2ba/notification-service
    container_name: notification-service
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      - config-server
      - postgres-notification-service
      - gateway-service
    environment:
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      CONFIG-TOKEN: ${CONFIG-TOKEN}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      DB_USERNAME: ${NOTIFICATION_DB_USERNAME}
      DB_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      DB_NAME: ${NOTIFICATION_DB_NAME}
      DB_PORT: ${NOTIFICATION_DB_PORT}

  postgres-user-service:
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "${USER_DB_PORT}:5432"

  user-service:
    image: max2ba/user-service
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - config-server
      - gateway-service
      - postgres-user-service
    environment:
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      CONFIG-TOKEN: ${CONFIG-TOKEN}
      DB_USERNAME: ${USER_DB_USERNAME}
      DB_PASSWORD: ${USER_DB_PASSWORD}
      DB_NAME: ${USER_DB_NAME}
      DB_URL: ${USER_DB_URL}
      DB_PORT: ${USER_DB_PORT}

  kafka-1:
    image: bitnami/kafka:3.4.0
    container_name: kafka-1
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=abcd1234abcd1234abcd12
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "19092:9092"
    networks:
      - microservices

  kafka-2:
    image: bitnami/kafka:3.4.0
    container_name: kafka-2
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=abcd1234abcd1234abcd12
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "29092:9092"
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
