server:
  port: 8082

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2s
        response-timeout: 3s
      server:
        webflux:
          enabled: true
          routes:
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: notificationCB
                    fallbackUri: forward:/fallback/notification
                    statusCodes:
                      - 500
                      - 501
                      - 502
                      - 503
                      - 504
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: userCB
                    fallbackUri: forward:/fallback/user
                    statusCodes:
                      - 500
                      - 501
                      - 502
                      - 503
                      - 504

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      notificationCB:
        registerHealthIndicator: true
        slidingWindowSize: 1
        minimumNumberOfCalls: 1
        failureRateThreshold: 1
        waitDurationInOpenState: 3s
        permittedNumberOfCallsInHalfOpenState: 1
      userCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 40
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      notificationCB:
        timeoutDuration: 5s
      userCB:
        timeoutDuration: 5s
